name: "Build and push image"
description: "Build and push an image to a registry"

inputs:
  service:
    description: "Service to build and push"
    required: true
  image_tag:
    description: Tag of image"
    required: true
  registry_repo:
    description: "Image registry repo"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Compose build ${{ inputs.service }}
      shell: bash
      run: docker-compose build ${{ inputs.service }}
      working-directory: ./src
      env:
        TAG: ${{ inputs.image_tag }}
        REGISTRY: ${{ inputs.registry_repo }}

    - name: Compose push ${{ inputs.service }}
      shell: bash
      run: docker-compose push ${{ inputs.service }}
      working-directory: ./src
      env:
        TAG: ${{ inputs.image_tag }}
        REGISTRY: ${{ inputs.registry_repo }}