version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - TwitterCredentials__ConsumerKey=${TWITTERCREDENTIALS_CONSUMERKEY}
      - TwitterCredentials__ConsumerSecret=${TWITTERCREDENTIALS_CONSUMERSECRET}
      - TwitterCredentials__AccessToken=${TWITTERCREDENTIALS_ACCESSTOKEN}
      - TwitterCredentials__AccessTokenSecret=${TWITTERCREDENTIALS_ACCESSTOKENSECRET}
    ports:
      - "6001:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  web:
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=80
    env_file:
      - ./Web/fletchling.web/.env
    ports:
      - "6002:80"
    volumes:
      - ./Web/fletchling.web:/app
      - /app/node_modules
      - /app/.next

  reverse-proxy:
    ports:
      - "80:80"
      - "443:443"

  seq:
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq_data:/data
    ports:
      - "8080:80"