name: Build and push Web image

on:
  push:
    branches:
      - master

    paths:
      - src/release_version/web.txt
      - .github/workflows/web-build-push.yml

env:
  SERVICE: web

jobs:
  BuildAndPushImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Web release version
        shell: bash
        run: |
          cd src/release_version/
          IMAGE_TAG=$( cat web.txt )
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "GIT_TAG=web-$IMAGE_TAG" >> $GITHUB_ENV

      - name: Check if Github tag exists
        id: checkTag
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ env.GIT_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github tag
        uses: actions/github-script@v3
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.GIT_TAG}`,
              sha: context.sha
            })

      - name: Build and push image to registry
        uses: ./.github/workflows/composite/build-push
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        with:
          service: ${{ env.SERVICE }}
          image_tag: ${{ env.IMAGE_TAG }}
          registry_repo: ${{ secrets.DOCKERHUB_REPO }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}